[package]
name = "blog-os"
version = "0.1.0"
authors = ["Andy Fang <andy.fang@airbnb.com>"]

[dependencies]
bootloader_precompiled = "0.2.0"

[package.metadata.bootimage]
default-target = "x86_64-blog-os.json"
