version: 2

defaults: &defaults
  docker:
    - image: buildpack-deps:stretch

build-defaults: &build-defaults
  docker:
      - image: andyfangdz/blog-os-buildenv

jobs:
  build-env:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - run: |
          IMAGE=andyfangdz/blog-os-buildenv
          TAG=circleci-build-$CIRCLE_BUILD_NUM
          GIT_SHA=$(git rev-parse HEAD | cut -c 1-6)
          docker build --target buildenv -t $IMAGE:$TAG -t $IMAGE:latest -t $IMAGE:git-$GIT_SHA .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $IMAGE

  test:
    <<: *build-defaults
    steps:
      - checkout
      - run:
          name: rustup component add rustfmt-preview
          command: rustup component add rustfmt-preview
      - run:
          name: cargo fmt
          command: cargo fmt --all -- --check
      - run:
          name: cargo build
          command: cargo build
      - run:
          name: cargo test
          command: cargo test

  build:
    <<: *build-defaults
    steps:
      - checkout
      - run:
          name: build kernel
          command: cargo xbuild --target x86_64-blog-os.json --release
      - run:
          name: build boot image
          command: bootimage build --release
      - store_artifacts:
          path: /root/project/target/x86_64-blog-os/release/bootimage-blog-os.bin
          destination: bootimage-blog-os.bin

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-env
      - test
      - build
  nightly-buildenv:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-env
