version: 2
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: install rust-src
          command: rustup component add rust-src
      - run:
          name: install xbuild
          command: cargo install cargo-xbuild
      - run:
          name: build kernel
          command: cargo xbuild --target x86_64-blog_os.json
