version: 2
jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: build kernel
          command: cargo xbuild --target x86_64-blog_os.json
