version: 2

defaults: &defaults
  docker:
    - image: buildpack-deps:stretch

jobs:
  build-env:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.06.0-ce
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - run: |
          IMAGE=andyfangdz/blog-os-buildenv
          TAG=circleci-build-$CIRCLE_BUILD_NUM
          GIT_SHA=$(git rev-parse HEAD | cut -c 1-6)
          docker build -t $IMAGE:$TAG -t $IMAGE:latest -t $IMAGE:git-$GIT_SHA .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $IMAGE

  build:
    docker:
      - image: andyfangdz/blog-os-buildenv
    steps:
      - checkout
      - run:
          name: build kernel
          command: cargo xbuild --target x86_64-blog-os.json
      - run:
          name: build boot image
          command: bootimage build

workflows:
  version: 2
  build-env-and-os:
    jobs:
      - build-env
      - build
  nightly-buildenv:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-env
