version: 2
jobs:
  build-env:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.05.0-ce
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - run: |
          IMAGE=andyfangdz/blog-os-buildenv
          TAG=circleci-build-$CIRCLE_BUILD_NUM
          docker build -t $IMAGE:$TAG -t latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $IMAGE

  build-os:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: install rust-src
          command: rustup component add rust-src
      - run:
          name: install xbuild
          command: cargo install cargo-xbuild
      - run:
          name: build kernel
          command: cargo xbuild --target x86_64-blogs.json
